![Numpy!](./numpy_logo.png "Numpy")

# Зачем нужен  NumPy?
![Numpy!](./array_vs_list.png "Numpy")

# SIMD - Single Instruction Multiply Data

# Подключаем библиотеку в проект

In [145]:
import numpy as np

# Сравниваем скорость с python

In [146]:
# Размер коллекции
size = 1_000_000 
  
# Создаем список в питоне
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
 
# Создаем массивы в numpy
array1 = np.arange(size)
array2 = np.arange(size)

In [147]:
%%time
dot_list = 0 
# list
for a, b in zip(list1, list2):
    dot_list += (a * b)

CPU times: user 144 ms, sys: 2.78 ms, total: 147 ms
Wall time: 146 ms


In [148]:
%%time
dot_numpy = np.dot(array1, array2)

CPU times: user 1.83 ms, sys: 720 µs, total: 2.55 ms
Wall time: 1.15 ms


In [149]:
dot_list

333332833333500000

In [150]:
dot_numpy

333332833333500000

# Основы

In [151]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [152]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [153]:
a.ndim

1

In [154]:
b.ndim

2

In [155]:
a.shape

(3,)

In [156]:
b.shape

(2, 3)

In [157]:
a.size

3

In [158]:
b.size

6

In [159]:
a.dtype

dtype('int32')

In [160]:
b.dtype

dtype('float64')

# Индексация

In [161]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype="int32")
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int32)

In [38]:
a[1,4]

12

In [162]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14], dtype=int32)

In [163]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14], dtype=int32)

In [40]:
a[:,1]

array([2, 9], dtype=int32)

In [46]:
a[0,1:4]

array([2, 3, 4], dtype=int32)

In [47]:
a[:,2] = [100, 101]
a

array([[  1,   2, 100,   4,   5,   6,   7],
       [  8,   9, 101,  11,  12,  13,  14]], dtype=int32)

# Удобные способы создания

In [49]:
a = np.zeros((5,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
a = np.ones((5,10), dtype='int32')
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [56]:
np.full((2,2), 42)

array([[42, 42],
       [42, 42]])

In [57]:
np.full_like(a, 15)

array([[15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]], dtype=int32)

In [59]:
np.random.rand(2,3)

array([[0.02518284, 0.77216455, 0.53643418],
       [0.80052422, 0.24615598, 0.98464549]])

In [61]:
np.random.randint(-5,5, size=(3,3))

array([[ 4, -2, -5],
       [-4, -3, -4],
       [-2,  4, -3]])

In [62]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.linspace(2.0, 3.0, num=100)

array([2.        , 2.01010101, 2.02020202, 2.03030303, 2.04040404,
       2.05050505, 2.06060606, 2.07070707, 2.08080808, 2.09090909,
       2.1010101 , 2.11111111, 2.12121212, 2.13131313, 2.14141414,
       2.15151515, 2.16161616, 2.17171717, 2.18181818, 2.19191919,
       2.2020202 , 2.21212121, 2.22222222, 2.23232323, 2.24242424,
       2.25252525, 2.26262626, 2.27272727, 2.28282828, 2.29292929,
       2.3030303 , 2.31313131, 2.32323232, 2.33333333, 2.34343434,
       2.35353535, 2.36363636, 2.37373737, 2.38383838, 2.39393939,
       2.4040404 , 2.41414141, 2.42424242, 2.43434343, 2.44444444,
       2.45454545, 2.46464646, 2.47474747, 2.48484848, 2.49494949,
       2.50505051, 2.51515152, 2.52525253, 2.53535354, 2.54545455,
       2.55555556, 2.56565657, 2.57575758, 2.58585859, 2.5959596 ,
       2.60606061, 2.61616162, 2.62626263, 2.63636364, 2.64646465,
       2.65656566, 2.66666667, 2.67676768, 2.68686869, 2.6969697 ,
       2.70707071, 2.71717172, 2.72727273, 2.73737374, 2.74747

# Операции

In [164]:
a = np.array([1,2,3,4])

In [165]:
a + 2

array([3, 4, 5, 6])

In [166]:
a - 1

array([0, 1, 2, 3])

In [167]:
a * 2

array([2, 4, 6, 8])

In [168]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [169]:
a ** 2

array([ 1,  4,  9, 16])

In [170]:
b = np.array([1,0,1,0])

In [172]:
a + b

array([2, 2, 4, 4])

In [173]:
a / b

/var/folders/9z/x5x5vgm95yjdl24m0nzx8m5w0000gn/T/ipykernel_85251/1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([ 1., inf,  3., inf])

In [174]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [176]:
np.log2(a)

array([0.       , 1.       , 1.5849625, 2.       ])

In [177]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [178]:
np.log?

# Статистика

In [183]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
np.min(stats)

1

In [181]:
np.min(stats, axis=1)

array([1, 4])

In [182]:
np.min(stats, axis=0)

array([1, 2, 3])

In [184]:
np.sum(stats, axis=1)

array([ 6, 15])

In [185]:
np.sum(stats)

21

In [188]:
np.mean(stats)

3.5

In [85]:
np.std(stats)

1.707825127659933

In [189]:
np.median(stats)

3.5

# Изменение формы

In [190]:
before = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
before

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [191]:
before.shape

(2, 6)

In [194]:
before.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [195]:
before.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [196]:
before.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [197]:
before.reshape((4,-1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [199]:
one_dim = before.reshape((-1))
one_dim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [200]:
one_dim.reshape((1,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [201]:
one_dim.reshape((3,-1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [202]:
one_dim.reshape((3,-1,1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [203]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [204]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [205]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])